name: ngs/image-card
group: NGS Content Elements
title: Image Card
description: small image left and text right with optional button
prefixFields: false
fields:
  - identifier: backgroundcolor
    label: 'Background Color'
    type: Select
    renderType: selectSingle
    items:
      - label: 'Primary'
        value: primary
      - label: 'Secondary'
        value: secondary
  - identifier: buttonstyle
    label: 'Button Style'
    type: Select
    renderType: selectSingle
    items:
      - label: 'Outlined'
        value: outlined
      - label: 'Filled'
        value: filled
  - identifier: inverse
    label: 'Inverse'
    type: Checkbox
    items:
      - label: 'inverse'
  - identifier: header
    useExistingField: true
  - identifier: bodytext
    useExistingField: true
    enableRichtext: true
  - identifier: linktext
    label: Link text
    type: Text
    max: 30
  - identifier: link
    label: Readmore link
    type: Link
