base: 'https://typo3-ngs.ddev.site/'
dependencies:
  - ngs-it/template
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    flag: us
rootPageId: 1
websiteTitle: ''
